// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tweetbook.Tests.Integration.Tests.FunctionalTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Comments")]
    public partial class CommentsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "Comments.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Comments", "\tIn order to perform actions with Comments\r\n\tAs Tweetbook user\r\n\tI want to list, " +
                    "create, edit and delete comments", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table125 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password"});
            table125.AddRow(new string[] {
                        "JohnDoe@mail.com",
                        "Dummy#123"});
            table125.AddRow(new string[] {
                        "JackSmith@box.com",
                        "qwerTy!098"});
#line 7
 testRunner.Given("Register Users", ((string)(null)), table125, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table126 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "PostTitle",
                        "PostContent",
                        "UserId"});
            table126.AddRow(new string[] {
                        "11111111-61a4-4714-b6cd-1b1dae19bdec",
                        "Post One",
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
                        "11111111-c97d-46e3-a3c9-6c4fd63cef9e"});
            table126.AddRow(new string[] {
                        "22222222-61a4-4714-b6cd-1b1dae19bdec",
                        "Post Two",
                        "Lectus urna duis convallis convallis tellus id interdum.",
                        "22222222-1111-46e3-a3c9-6c4fd63cef9e"});
            table126.AddRow(new string[] {
                        "33333333-61a4-4714-b6cd-1b1dae19bdec",
                        "Post Three",
                        "Diam quam nulla porttitor massa id neque aliquam vestibulum.",
                        "22222222-1111-46e3-a3c9-6c4fd63cef9e"});
            table126.AddRow(new string[] {
                        "44444444-61a4-4714-b6cd-1b1dae19bdec",
                        "Post Four",
                        "Parturient montes nascetur ridiculus mus mauris.",
                        "33333333-1111-46e3-a3c9-6c4fd63cef9e"});
#line 11
 testRunner.Given("\"Post\" records exist in database", ((string)(null)), table126, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table127 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "UserId",
                        "PostId",
                        "CommentContent"});
            table127.AddRow(new string[] {
                        "11111111-61a4-4714-b6cd-1b1dae19bdec",
                        "c913181d-c97d-46e3-a3c9-6c4fd63cef9e",
                        "11111111-61a4-4714-b6cd-1b1dae19bdec",
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"});
            table127.AddRow(new string[] {
                        "22222222-61a4-4714-b6cd-1b1dae19bdec",
                        "c913181d-c97d-46e3-a3c9-6c4fd63cef9e",
                        "11111111-61a4-4714-b6cd-1b1dae19bdec",
                        "Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."});
            table127.AddRow(new string[] {
                        "33333333-61a4-4714-b6cd-1b1dae19bdec",
                        "00000000-c97d-46e3-a3c9-6c4fd63cef9e",
                        "22222222-61a4-4714-b6cd-1b1dae19bdec",
                        "Et odio pellentesque diam volutpat commodo."});
            table127.AddRow(new string[] {
                        "44444444-61a4-4714-b6cd-1b1dae19bdec",
                        "00000000-37fc-4f48-834d-f95608414c7f",
                        "22222222-61a4-4714-b6cd-1b1dae19bdec",
                        "Nullam eget felis eget nunc lobortis mattis."});
            table127.AddRow(new string[] {
                        "55555555-61a4-4714-b6cd-1b1dae19bdec",
                        "11111111-37fc-4f48-834d-f95608414c7f",
                        "33333333-61a4-4714-b6cd-1b1dae19bdec",
                        "Lectus urna duis convallis convallis tellus id interdum."});
#line 17
 testRunner.Given("\"Comment\" records exist in database", ((string)(null)), table127, "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User can create new comments, update and delete his comments")]
        public virtual void UserCanCreateNewCommentsUpdateAndDeleteHisComments()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User can create new comments, update and delete his comments", null, ((string[])(null)));
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table128 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table128.AddRow(new string[] {
                            "JohnDoe@mail.com",
                            "Dummy#123"});
#line 27
 testRunner.When("Login as", ((string)(null)), table128, "When ");
#line hidden
                TechTalk.SpecFlow.Table table129 = new TechTalk.SpecFlow.Table(new string[] {
                            "PostId",
                            "CommentContent"});
                table129.AddRow(new string[] {
                            "22222222-61a4-4714-b6cd-1b1dae19bdec",
                            ".NET Core fully supports C#"});
#line 30
 testRunner.When("Create new \"Comment\" object", ((string)(null)), table129, "When ");
#line hidden
                TechTalk.SpecFlow.Table table130 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentContent",
                            "PostId"});
                table130.AddRow(new string[] {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table130.AddRow(new string[] {
                            "Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt.",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table130.AddRow(new string[] {
                            "Et odio pellentesque diam volutpat commodo.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table130.AddRow(new string[] {
                            "Nullam eget felis eget nunc lobortis mattis.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table130.AddRow(new string[] {
                            "Lectus urna duis convallis convallis tellus id interdum.",
                            "33333333-61a4-4714-b6cd-1b1dae19bdec"});
                table130.AddRow(new string[] {
                            ".NET Core fully supports C#",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
#line 33
 testRunner.Then("Assert get all \"Comment\" returns list of objects", ((string)(null)), table130, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table131 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentContent"});
                table131.AddRow(new string[] {
                            ".NET Core fully supports C# and F# and partially supports Visual Basic .NET."});
#line 41
 testRunner.When("Update \"Comment\" object where \"CommentContent\" is \".NET Core fully supports C#\"", ((string)(null)), table131, "When ");
#line hidden
                TechTalk.SpecFlow.Table table132 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentContent",
                            "PostId"});
                table132.AddRow(new string[] {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table132.AddRow(new string[] {
                            "Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt.",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table132.AddRow(new string[] {
                            "Et odio pellentesque diam volutpat commodo.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table132.AddRow(new string[] {
                            "Nullam eget felis eget nunc lobortis mattis.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table132.AddRow(new string[] {
                            "Lectus urna duis convallis convallis tellus id interdum.",
                            "33333333-61a4-4714-b6cd-1b1dae19bdec"});
                table132.AddRow(new string[] {
                            ".NET Core fully supports C# and F# and partially supports Visual Basic .NET.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
#line 44
 testRunner.Then("Assert get all \"Comment\" returns list of objects", ((string)(null)), table132, "Then ");
#line hidden
#line 52
 testRunner.When("Delete \"Comment\" object where \"CommentContent\" is \".NET Core fully supports C# an" +
                        "d F# and partially supports Visual Basic .NET.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table133 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentContent",
                            "PostId"});
                table133.AddRow(new string[] {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table133.AddRow(new string[] {
                            "Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt.",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table133.AddRow(new string[] {
                            "Et odio pellentesque diam volutpat commodo.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table133.AddRow(new string[] {
                            "Nullam eget felis eget nunc lobortis mattis.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table133.AddRow(new string[] {
                            "Lectus urna duis convallis convallis tellus id interdum.",
                            "33333333-61a4-4714-b6cd-1b1dae19bdec"});
#line 53
 testRunner.Then("Assert get all \"Comment\" returns list of objects", ((string)(null)), table133, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User can not delete or update not his comments")]
        public virtual void UserCanNotDeleteOrUpdateNotHisComments()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User can not delete or update not his comments", null, ((string[])(null)));
#line 62
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table134 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table134.AddRow(new string[] {
                            "JohnDoe@mail.com",
                            "Dummy#123"});
#line 63
 testRunner.When("Login as", ((string)(null)), table134, "When ");
#line hidden
                TechTalk.SpecFlow.Table table135 = new TechTalk.SpecFlow.Table(new string[] {
                            "PostId",
                            "CommentContent"});
                table135.AddRow(new string[] {
                            "22222222-61a4-4714-b6cd-1b1dae19bdec",
                            ".NET Core fully supports C#"});
#line 66
 testRunner.When("Create new \"Comment\" object", ((string)(null)), table135, "When ");
#line hidden
                TechTalk.SpecFlow.Table table136 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table136.AddRow(new string[] {
                            "JackSmith@box.com",
                            "qwerTy!098"});
#line 69
 testRunner.When("Login as", ((string)(null)), table136, "When ");
#line hidden
                TechTalk.SpecFlow.Table table137 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentContent",
                            "PostId"});
                table137.AddRow(new string[] {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table137.AddRow(new string[] {
                            "Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt.",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table137.AddRow(new string[] {
                            "Et odio pellentesque diam volutpat commodo.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table137.AddRow(new string[] {
                            "Nullam eget felis eget nunc lobortis mattis.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table137.AddRow(new string[] {
                            "Lectus urna duis convallis convallis tellus id interdum.",
                            "33333333-61a4-4714-b6cd-1b1dae19bdec"});
                table137.AddRow(new string[] {
                            ".NET Core fully supports C#",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
#line 72
 testRunner.Then("Assert get all \"Comment\" returns list of objects", ((string)(null)), table137, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table138 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentContent"});
                table138.AddRow(new string[] {
                            "Trying to update not my post! Should not be allowed"});
#line 80
 testRunner.When("Update \"Comment\" object where \"CommentContent\" is \".NET Core fully supports C#\"", ((string)(null)), table138, "When ");
#line hidden
                TechTalk.SpecFlow.Table table139 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentContent",
                            "PostId"});
                table139.AddRow(new string[] {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table139.AddRow(new string[] {
                            "Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt.",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table139.AddRow(new string[] {
                            "Et odio pellentesque diam volutpat commodo.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table139.AddRow(new string[] {
                            "Nullam eget felis eget nunc lobortis mattis.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table139.AddRow(new string[] {
                            "Lectus urna duis convallis convallis tellus id interdum.",
                            "33333333-61a4-4714-b6cd-1b1dae19bdec"});
                table139.AddRow(new string[] {
                            ".NET Core fully supports C#",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
#line 83
 testRunner.Then("Assert get all \"Comment\" returns list of objects", ((string)(null)), table139, "Then ");
#line hidden
#line 91
 testRunner.When("Delete \"Comment\" object where \"CommentContent\" is \".NET Core fully supports C#\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table140 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentContent",
                            "PostId"});
                table140.AddRow(new string[] {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table140.AddRow(new string[] {
                            "Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt.",
                            "11111111-61a4-4714-b6cd-1b1dae19bdec"});
                table140.AddRow(new string[] {
                            "Et odio pellentesque diam volutpat commodo.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table140.AddRow(new string[] {
                            "Nullam eget felis eget nunc lobortis mattis.",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
                table140.AddRow(new string[] {
                            "Lectus urna duis convallis convallis tellus id interdum.",
                            "33333333-61a4-4714-b6cd-1b1dae19bdec"});
                table140.AddRow(new string[] {
                            ".NET Core fully supports C#",
                            "22222222-61a4-4714-b6cd-1b1dae19bdec"});
#line 92
 testRunner.Then("Assert get all \"Comment\" returns list of objects", ((string)(null)), table140, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
